# Generated by Django 3.0.2 on 2020-01-06 20:15

from django.db import migrations, models
import prueba1.validators


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0004_auto_20200102_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha_creacion',
            field=models.DateField(validators=[prueba1.validators.past_validator]),
        ),
    ]
