# Generated by Django 3.0.2 on 2020-04-01 13:27

from django.db import migrations, models
import django.db.models.deletion
import prueba1.validators


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0011_auto_20200313_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('borrador', models.BooleanField()),
                ('cerrada', models.BooleanField()),
                ('vetada', models.BooleanField()),
                ('motivo_veto', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_creacion', models.DateField(validators=[prueba1.validators.past_validator])),
                ('identificador', models.CharField(max_length=30, unique=True)),
                ('actividades', models.ManyToManyField(to='prueba1.Actividad')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba1.Usuario')),
            ],
        ),
    ]
